Repository seladb/PcapPlusPlus, pull requests merged in 2024-07, with the labels that each got.

#1478 Auto precommit update
  .pre-commit-config.yaml
Labels: automated-pr

#1477 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1475 Port code to use `getAndDetach` and deprecate `getAndRemoveFromVector`.
  Common++/header/PointerVector.h
  Packet++/src/TcpReassembly.cpp
  Tests/Pcap++Test/Tests/LiveDeviceTests.cpp
Labels: refactoring

#1483 cmake: use Ccache if it's available
  CMakeLists.txt
Labels: enhancement, build

#1476 Refactor of `PcapRemoteDeviceList`'s factory functions.
  Pcap++/header/PcapRemoteDeviceList.h
  Pcap++/src/PcapRemoteDeviceList.cpp
Labels: enhancement, refactoring

#1487 Fix memory leak in PointerVector pushBack
  Common++/header/PointerVector.h
  Packet++/header/Asn1Codec.h
  Packet++/src/LdapLayer.cpp
Labels: bug

#1500 Add getter to fetch all IP addresses of a live device as IPAddress objects.
  Pcap++/header/PcapLiveDevice.h
  Pcap++/src/PcapLiveDevice.cpp
  Tests/Pcap++Test/Tests/LiveDeviceTests.cpp
Labels: refactoring
