Repository seladb/PcapPlusPlus, pull requests merged in 2024-06, with the labels that each got.

#1415 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1416 Auto precommit update
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  Packet++/header/SipLayer.h
Labels: automated-pr

#1425 github: ci: fix pipeline due to bump of GCC in mingw
  3rdParty/LightPcapNg/CMakeLists.txt
Labels: 3rd-party, CI

#1427 Added NUMA awareness for DpdkDevice (Issue #1414)
  Pcap++/header/DpdkDevice.h
  Pcap++/src/DpdkDevice.cpp
Labels: enhancement, dpdk

#1442 Optimized allocation of buffers when fetching DNS on windows.
  Pcap++/src/PcapLiveDeviceList.cpp
Labels: refactoring

#1446 Refactor executeShellCommand to throw exceptions.
  Common++/header/SystemUtils.h
  Common++/src/SystemUtils.cpp
  Examples/KniPong/main.cpp
  Pcap++/src/DpdkDeviceList.cpp
  Pcap++/src/PfRingDeviceList.cpp
Labels: refactoring

#1441 Use smart pointers for RemoteAuthentication in PcapRemoteDeviceList.
  Pcap++/header/PcapRemoteDevice.h
  Pcap++/header/PcapRemoteDeviceList.h
  Pcap++/src/PcapRemoteDevice.cpp
  Pcap++/src/PcapRemoteDeviceList.cpp
Labels: refactoring

#1443 Cpp11 refactor of remote device.
  Pcap++/header/PcapRemoteDevice.h
  Pcap++/src/PcapRemoteDevice.cpp
Labels: refactoring

#1445 Refactor of PfRingDeviceList internals.
  Pcap++/header/PfRingDeviceList.h
  Pcap++/src/PfRingDeviceList.cpp
Labels: refactoring

#1455 Fixed unhandled exceptions crashing the entire test suite.
  Tests/PcppTestFramework/PcppTestFrameworkRun.h
Labels: bug, tests

#1471 Refactored clang version check into a python script.
  .pre-commit-config.yaml
  ci/check-clang-format-version.py
  ci/check-clang-format-version.sh
Labels: CI

#1468 `PointerVector` smart pointer intergration.
  Common++/header/PointerVector.h
Labels: enhancement, refactoring
