Repository seladb/PcapPlusPlus, pull requests merged in 2024-10, with the labels that each got.

#1598 Auto precommit update
  .pre-commit-config.yaml
Labels: automated-pr

#1597 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1613 Print error messages from python tests
  ci/run_tests/run_tests.py
  ci/run_tests/run_tests_windows.py
Labels: tests

#1497 Change PcapLiveDevice to store IP information as IPAddresses.
  Pcap++/header/PcapLiveDevice.h
  Pcap++/header/PcapRemoteDevice.h
  Pcap++/header/WinPcapLiveDevice.h
  Pcap++/src/PcapLiveDevice.cpp
  Pcap++/src/PcapLiveDeviceList.cpp
  Pcap++/src/PcapRemoteDevice.cpp
  Pcap++/src/PcapRemoteDeviceList.cpp
  Pcap++/src/WinPcapLiveDevice.cpp
  Tests/Pcap++Test/Tests/LiveDeviceTests.cpp
Labels: bug, refactoring, breaking change

#1602 Improve pre-commit workflow in CI
  .cmake-format
  .codespellrc
  .gersemirc
  .github/workflows/build_and_test.yml
  .pre-commit-config.yaml
  3rdParty/CMakeLists.txt
  3rdParty/LightPcapNg/LightPcapNg/cmake/FindZSTD.cmake
  CMakeLists.txt
  ci/clang-tidy-all.sh
  ci/cmake-format-all.sh
  cmake/modules/FindBPF.cmake
  cmake/modules/FindDPDK.cmake
  cmake/modules/FindNUMA.cmake
  cmake/modules/FindPCAP.cmake
  cmake/modules/FindPF_RING.cmake
  cmake/modules/FindPacket.cmake
  cmake/modules/FindZSTD.cmake
  cmake/modules/PcapPlusPlusUtils.cmake
  cmake/modules/TargetArch.cmake
Labels: CI

#1609 Bump macos version
  .github/workflows/build_and_test.yml
  .github/workflows/package.yml
  codecov.yml
Labels: CI

#1589 add zh-tw README
  README.md
  translation/README-zh-tw.md
Labels: documentation
