Repository seladb/PcapPlusPlus, pull requests merged in 2024-08, with the labels that each got.

#1518 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1519 Auto precommit update
  .pre-commit-config.yaml
  Packet++/header/SSHLayer.h
  cmake/package/READMEs/release_notes.txt
Labels: automated-pr

#1486 support ubuntu 24 in CI
  .github/workflows/build_and_test.yml
  .github/workflows/package.yml
Labels: CI

#1532 Added a RAII PcapHandle wrapper class that manages a Pcap handle.
  Pcap++/header/PcapDevice.h
  Pcap++/src/PcapDevice.cpp
  Pcap++/src/PcapFileDevice.cpp
  Pcap++/src/PcapLiveDevice.cpp
  Pcap++/src/PcapRemoteDevice.cpp
  Pcap++/src/WinPcapLiveDevice.cpp
Labels: enhancement
