Repository seladb/PcapPlusPlus, pull requests merged in 2024-09, with the labels that each got.

#1561 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1560 Auto precommit update
  .pre-commit-config.yaml
  Packet++/header/SSLHandshake.h
Labels: automated-pr

#1559 Added ProtocolType to Layer constructor.
  Packet++/header/ArpLayer.h
  Packet++/header/BgpLayer.h
  Packet++/header/CotpLayer.h
  Packet++/header/EthDot3Layer.h
  Packet++/header/EthLayer.h
  Packet++/header/FtpLayer.h
  Packet++/header/GreLayer.h
  Packet++/header/GtpLayer.h
  Packet++/header/HttpLayer.h
  Packet++/header/IPSecLayer.h
  Packet++/header/IcmpLayer.h
  Packet++/header/IcmpV6Layer.h
  Packet++/header/IgmpLayer.h
  Packet++/header/LLCLayer.h
  Packet++/header/Layer.h
  Packet++/header/MplsLayer.h
  Packet++/header/NflogLayer.h
  Packet++/header/NtpLayer.h
  Packet++/header/NullLoopbackLayer.h
  Packet++/header/PPPoELayer.h
  Packet++/header/PacketTrailerLayer.h
  Packet++/header/PayloadLayer.h
  Packet++/header/RadiusLayer.h
  Packet++/header/S7CommLayer.h
  Packet++/header/SSHLayer.h
  Packet++/header/SSLLayer.h
  Packet++/header/SingleCommandTextProtocol.h
  Packet++/header/SipLayer.h
  Packet++/header/Sll2Layer.h
  Packet++/header/SllLayer.h
  Packet++/header/SmtpLayer.h
  Packet++/header/SomeIpLayer.h
  Packet++/header/StpLayer.h
  Packet++/header/TelnetLayer.h
  Packet++/header/TextBasedProtocol.h
  Packet++/header/TpktLayer.h
  Packet++/header/UdpLayer.h
  Packet++/header/VlanLayer.h
  Packet++/header/VrrpLayer.h
  Packet++/header/VxlanLayer.h
  Packet++/header/WakeOnLanLayer.h
  Packet++/src/DhcpLayer.cpp
  Packet++/src/DhcpV6Layer.cpp
  Packet++/src/HttpLayer.cpp
  Packet++/src/IPv6Layer.cpp
  Packet++/src/LdapLayer.cpp
  Packet++/src/SdpLayer.cpp
  Packet++/src/SingleCommandTextProtocol.cpp
  Packet++/src/SipLayer.cpp
  Packet++/src/TcpLayer.cpp
  Packet++/src/TextBasedProtocol.cpp
Labels: refactoring

#1563 Updated Packet++ headers to use `override` and Cpp type casts.
  Packet++/header/ArpLayer.h
  Packet++/header/BgpLayer.h
  Packet++/header/CotpLayer.h
  Packet++/header/DhcpLayer.h
  Packet++/header/DhcpV6Layer.h
  Packet++/header/DnsLayer.h
  Packet++/header/DnsResource.h
  Packet++/header/DnsResourceData.h
  Packet++/header/EthDot3Layer.h
  Packet++/header/EthLayer.h
  Packet++/header/FtpLayer.h
  Packet++/header/GreLayer.h
  Packet++/header/GtpLayer.h
  Packet++/header/HttpLayer.h
  Packet++/header/IPLayer.h
  Packet++/header/IPReassembly.h
  Packet++/header/IPSecLayer.h
  Packet++/header/IPv4Layer.h
  Packet++/header/IPv6Extensions.h
  Packet++/header/IPv6Layer.h
  Packet++/header/IcmpLayer.h
  Packet++/header/IcmpV6Layer.h
  Packet++/header/IgmpLayer.h
  Packet++/header/LLCLayer.h
  Packet++/header/Layer.h
  Packet++/header/LdapLayer.h
  Packet++/header/MplsLayer.h
  Packet++/header/NdpLayer.h
  Packet++/header/NflogLayer.h
  Packet++/header/NtpLayer.h
  Packet++/header/NullLoopbackLayer.h
  Packet++/header/PPPoELayer.h
  Packet++/header/PacketTrailerLayer.h
  Packet++/header/PayloadLayer.h
  Packet++/header/RadiusLayer.h
  Packet++/header/S7CommLayer.h
  Packet++/header/SSHLayer.h
  Packet++/header/SSLHandshake.h
  Packet++/header/SSLLayer.h
  Packet++/header/SdpLayer.h
  Packet++/header/SipLayer.h
  Packet++/header/Sll2Layer.h
  Packet++/header/SllLayer.h
  Packet++/header/SmtpLayer.h
  Packet++/header/SomeIpLayer.h
  Packet++/header/SomeIpSdLayer.h
  Packet++/header/StpLayer.h
  Packet++/header/TLVData.h
  Packet++/header/TcpLayer.h
  Packet++/header/TelnetLayer.h
  Packet++/header/TextBasedProtocol.h
  Packet++/header/TpktLayer.h
  Packet++/header/UdpLayer.h
  Packet++/header/VlanLayer.h
  Packet++/header/VrrpLayer.h
  Packet++/header/VxlanLayer.h
  Packet++/header/WakeOnLanLayer.h
  cppcheckSuppressions.txt
Labels: refactoring

#1557 Add WireGuard protocol support
  Common++/header/Logger.h
  Packet++/CMakeLists.txt
  Packet++/header/ProtocolType.h
  Packet++/header/WireGuardLayer.h
  Packet++/src/UdpLayer.cpp
  Packet++/src/WireGuardLayer.cpp
  README.md
  Tests/Packet++Test/CMakeLists.txt
  Tests/Packet++Test/PacketExamples/WireGuard.pcap
  Tests/Packet++Test/PacketExamples/WireGuardCookieReply.dat
  Tests/Packet++Test/PacketExamples/WireGuardHandshakeInitiation.dat
  Tests/Packet++Test/PacketExamples/WireGuardHandshakeResponse.dat
  Tests/Packet++Test/PacketExamples/WireGuardTransportData.dat
  Tests/Packet++Test/TestDefinition.h
  Tests/Packet++Test/Tests/WireGuardTests.cpp
  Tests/Packet++Test/main.cpp
Labels: enhancement
