Repository seladb/PcapPlusPlus, pull requests merged in 2025-03, with the labels that each got.

#1723 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1724 Auto precommit update
  .pre-commit-config.yaml
  cmake/setup_dpdk.py
Labels: automated-pr

#1734 Exported set thread affinity code to a helper function.
  Pcap++/src/PfRingDevice.cpp
Labels: refactoring, dpdk

#1733 Adds CMake variable to configure compile time log levels.
  CMakeLists.txt
Labels: enhancement, build

#1735 Added `noexcept` specifier to custom deleters throughout the project.
  Common++/src/SystemUtils.cpp
  Pcap++/header/PcapFilter.h
  Pcap++/header/PcapUtils.h
  Pcap++/src/PcapFilter.cpp
  Pcap++/src/PcapUtils.cpp
  Pcap++/src/PfRingDeviceList.cpp
Labels: refactoring

#1736 Change `PfRingDevice::m_CoreConfiguration` to std::array
  Common++/header/SystemUtils.h
  Pcap++/header/PfRingDevice.h
  Pcap++/src/PfRingDevice.cpp
Labels: refactoring

#1737 FIxed reentrant mode allocated buffer going out of scope.
  Pcap++/src/PfRingDevice.cpp
Labels: bug

#1745 Reorders the implementation order of PcapFileDevice.cpp to match the header declaration order.
  Pcap++/src/PcapFileDevice.cpp
Labels: refactoring

#1746 Changes PfRingDevice::m_StopThread to atomic.
  Pcap++/header/PfRingDevice.h
  Pcap++/src/PfRingDevice.cpp
Labels: refactoring

#1751 Replaced raw array of pointers with std::vector.
  Pcap++/header/PfRingDevice.h
  Pcap++/src/PfRingDevice.cpp
Labels: refactoring

#1752 Moved `setFilter` pcap implementation to `PcapHandle`.
  Pcap++/header/PcapDevice.h
  Pcap++/src/PcapDevice.cpp
Labels: refactoring
