Repository seladb/PcapPlusPlus, pull requests merged in 2025-05, with the labels that each got.

#1798 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1799 Auto precommit update
  .pre-commit-config.yaml
Labels: automated-pr

#1795 Updated `PfRingDeviceList` to use `internal::DeviceListBase`
  Pcap++/header/PfRingDeviceList.h
  Pcap++/src/PfRingDeviceList.cpp
Labels: refactoring

#1796 Updated `DpdkDeviceList` to use `internal::DeviceListBase`.
  Common++/header/PointerVector.h
  Pcap++/header/DpdkDeviceList.h
  Pcap++/src/DpdkDeviceList.cpp
Labels: refactoring

#1797 Updated `KniDeviceList` to use `internal::DeviceListBase`.
  Common++/header/PointerVector.h
  Pcap++/header/KniDeviceList.h
  Pcap++/src/KniDeviceList.cpp
Labels: refactoring

#1805 Replaced usages of `void*` to `internal::LightPcapNgHandle*`
  Pcap++/header/PcapFileDevice.h
  Pcap++/src/PcapFileDevice.cpp
Labels: refactoring

#1806 Cleanup of `PcapFileWriterDevice::open`
  Pcap++/header/PcapFileDevice.h
  Pcap++/src/PcapFileDevice.cpp
Labels: refactoring

#1810 Updated `RemoteDeviceList` and `PfRingDeviceList`'s getDevice API to match the rest.
  Pcap++/header/PcapRemoteDeviceList.h
  Pcap++/header/PfRingDeviceList.h
  Pcap++/src/PcapRemoteDeviceList.cpp
  Pcap++/src/PfRingDeviceList.cpp
Labels: refactoring, API deprecation

#1811 Extracted a separate interface for `getStatistics` methods.
  Pcap++/header/PcapDevice.h
  Pcap++/src/PcapDevice.cpp
Labels: refactoring

#1821 Bump the minimum required C++ Standard to 14
  CMakeLists.txt
  Common++/CMakeLists.txt
  Examples/CMakeLists.txt
  Packet++/CMakeLists.txt
  Pcap++/CMakeLists.txt
Labels: enhancement, build, API breaking change

#1828 Updated PCPP_DEPRECATED macro to use cpp14 [[deprecated]] attribute.
  Common++/header/DeprecationUtils.h
Labels: refactoring

#1785 Separated `PcapLiveDevice` statistics update worker under its own class.
  Pcap++/header/PcapDevice.h
  Pcap++/header/PcapLiveDevice.h
  Pcap++/src/PcapDevice.cpp
  Pcap++/src/PcapLiveDevice.cpp
Labels: refactoring

#1827 Added new overload `sendPacket(Packet const& packet, bool checkMtu)`
  Examples/ArpSpoofing/main.cpp
  Examples/DnsSpoofing/main.cpp
  Examples/IcmpFileTransfer/Common.cpp
  Pcap++/header/PcapLiveDevice.h
  Pcap++/src/NetworkUtils.cpp
  Pcap++/src/PcapLiveDevice.cpp
  Tests/Pcap++Test/Tests/LiveDeviceTests.cpp
Labels: refactoring, API deprecation

#1832 Refactored overrides of `WinPcapLiveDevice::startCapture`.
  Pcap++/header/PcapLiveDevice.h
  Pcap++/header/WinPcapLiveDevice.h
  Pcap++/src/PcapLiveDevice.cpp
  Pcap++/src/WinPcapLiveDevice.cpp
Labels: refactoring, API deprecation
