Repository seladb/PcapPlusPlus, pull requests merged in 2025-07, with the labels that each got.

#1857 CI: windows, remove 2019, add 2025
  .github/workflows/build_and_test.yml
  .github/workflows/package.yml
  cmake/package/READMEs/README.release.win.vs
Labels: Windows, CI

#1856 Auto precommit update
  .pre-commit-config.yaml
Labels: automated-pr

#1855 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1872 Added a warning log level.
  Common++/header/Logger.h
  Tests/Pcap++Test/Tests/LoggerTests.cpp
Labels: refactoring

#1893 Cast and smart pointer improvements.
  Packet++/src/Packet.cpp
Labels: refactoring

#1887 Added pure parsing benchmark
  Examples/PcapPlusPlus-benchmark/README.md
  Examples/PcapPlusPlus-benchmark/benchmark-google.cpp
Labels: enhancement

#1897 Disabled concurrency cancellation for master and dev branch.
  .github/workflows/build_and_test.yml
  .github/workflows/cifuzz.yml
  .github/workflows/doxygen.yml
Labels: CI

#1880 Improvements on lazy decoding of Asn1Codec.
  Packet++/header/Asn1Codec.h
  Packet++/src/Asn1Codec.cpp
Labels: refactoring

#1892 Updated Logger to use `std::function`
  Common++/header/Logger.h
Labels: refactoring

#1902 Moved the default log printer to have internal linkage.
  Common++/header/Logger.h
  Common++/src/Logger.cpp
Labels: refactoring
