Repository seladb/PcapPlusPlus, pull requests merged in 2025-06, with the labels that each got.

#1839 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1842 Cleanup of RawPacket construction.
  Packet++/header/RawPacket.h
  Packet++/src/RawPacket.cpp
  Pcap++/header/MBufRawPacket.h
Labels: refactoring

#1833 Added guard clause to `stopCapture` to prevent incomplete shutdown.
  Pcap++/header/PcapLiveDevice.h
  Pcap++/src/PcapLiveDevice.cpp
Labels: bug

#1834 Extracted MTU check code into its own helper functions.
  Pcap++/header/PcapLiveDevice.h
  Pcap++/src/PcapLiveDevice.cpp
Labels: refactoring
