Repository seladb/PcapPlusPlus, pull requests merged in 2025-09, with the labels that each got.

#1930 Fix telnet off by one error.
  Common++/CMakeLists.txt
  Common++/header/AssertionUtils.h
  Packet++/header/TelnetLayer.h
  Packet++/src/TelnetLayer.cpp
Labels: bug

#1929 Partial update tests to use new resource system.
  Tests/Packet++Test/PacketExamples/GREv0_4.dat
  Tests/Packet++Test/PacketExamples/dhcpv6_1.dat
  Tests/Packet++Test/PacketExamples/ftpIpv4CmdOnlyReq.dat
  Tests/Packet++Test/PacketExamples/ipv4-malformed1.dat
  Tests/Packet++Test/PacketExamples/nflogPacket.dat
  Tests/Packet++Test/PacketExamples/ssl-malformed1.dat
  Tests/Packet++Test/Tests/BgpTests.cpp
  Tests/Packet++Test/Tests/CiscoHdlcTests.cpp
  Tests/Packet++Test/Tests/CotpTests.cpp
  Tests/Packet++Test/Tests/DhcpTests.cpp
  Tests/Packet++Test/Tests/DhcpV6Tests.cpp
  Tests/Packet++Test/Tests/DnsTests.cpp
  Tests/Packet++Test/Tests/DoIpTests.cpp
  Tests/Packet++Test/Tests/EthAndArpTests.cpp
  Tests/Packet++Test/Tests/FtpTests.cpp
  Tests/Packet++Test/Tests/GreTests.cpp
  Tests/Packet++Test/Tests/GtpTests.cpp
  Tests/Packet++Test/Tests/HttpTests.cpp
  Tests/Packet++Test/Tests/IPSecTests.cpp
  Tests/Packet++Test/Tests/IPv4Tests.cpp
  Tests/Packet++Test/Tests/IPv6Tests.cpp
  Tests/Packet++Test/Tests/IcmpTests.cpp
  Tests/Packet++Test/Tests/IcmpV6Tests.cpp
  Tests/Packet++Test/Tests/IgmpTests.cpp
  Tests/Packet++Test/Tests/LLCTests.cpp
  Tests/Packet++Test/Tests/LdapTests.cpp
  Tests/Packet++Test/Tests/NflogTests.cpp
  Tests/Packet++Test/Tests/NtpTests.cpp
  Tests/Packet++Test/Tests/PPPoETests.cpp
  Tests/Packet++Test/Tests/PacketTests.cpp
  Tests/Packet++Test/Tests/RadiusTests.cpp
  Tests/Packet++Test/Tests/S7CommTests.cpp
  Tests/Packet++Test/Tests/SSHTests.cpp
  Tests/Packet++Test/Tests/SSLTests.cpp
  Tests/Packet++Test/Tests/SipSdpTests.cpp
  Tests/Packet++Test/Tests/Sll2Tests.cpp
  Tests/Packet++Test/Tests/SllNullLoopbackTests.cpp
  Tests/Packet++Test/Tests/SmtpTests.cpp
  Tests/Packet++Test/Tests/SomeIpSdTests.cpp
  Tests/Packet++Test/Tests/SomeIpTests.cpp
  Tests/Packet++Test/Tests/StpTests.cpp
  Tests/Packet++Test/Tests/TcpTests.cpp
  Tests/Packet++Test/Tests/TelnetTests.cpp
  Tests/Packet++Test/Tests/TpktTests.cpp
  Tests/Packet++Test/Tests/VlanMplsTests.cpp
  Tests/Packet++Test/Tests/VrrpTest.cpp
  Tests/Packet++Test/Tests/WakeOnLanTests.cpp
  Tests/Packet++Test/Tests/WireGuardTests.cpp
Labels: tests, refactoring

#1944 Partial tests update to use the new resource system - Part 3
  Tests/Packet++Test/Tests/DhcpTests.cpp
  Tests/Packet++Test/Tests/EthAndArpTests.cpp
  Tests/Packet++Test/Tests/GreTests.cpp
  Tests/Packet++Test/Tests/GtpTests.cpp
  Tests/Packet++Test/Tests/HttpTests.cpp
  Tests/Packet++Test/Tests/IPv4Tests.cpp
  Tests/Packet++Test/Tests/IcmpTests.cpp
  Tests/Packet++Test/Tests/IcmpV6Tests.cpp
  Tests/Packet++Test/Tests/IgmpTests.cpp
  Tests/Packet++Test/Tests/PPPoETests.cpp
  Tests/Packet++Test/Tests/PacketTests.cpp
  Tests/Packet++Test/Tests/Sll2Tests.cpp
  Tests/Packet++Test/Tests/SllNullLoopbackTests.cpp
  Tests/Packet++Test/Tests/SomeIpSdTests.cpp
  Tests/Packet++Test/Tests/SomeIpTests.cpp
  Tests/Packet++Test/Tests/TcpTests.cpp
  Tests/Packet++Test/Tests/VlanMplsTests.cpp
  Tests/Packet++Test/Tests/VrrpTest.cpp
  Tests/PcppTestUtilities/Resources.cpp
  Tests/PcppTestUtilities/Resources.h
Labels: tests, refactoring

#1961 Remove protected field `m_DeviceOpened` from `IDevice` interface.
  Pcap++/header/Device.h
  Pcap++/header/DpdkDevice.h
  Pcap++/header/KniDevice.h
  Pcap++/header/PcapFileDevice.h
  Pcap++/header/PcapLiveDevice.h
  Pcap++/header/PfRingDevice.h
  Pcap++/header/RawSocketDevice.h
  Pcap++/header/XdpDevice.h
  Pcap++/src/PcapDevice.cpp
Labels: refactoring

#1968 Refactor: Add override specifier to MBufRawPacket virtual methods
  Pcap++/header/MBufRawPacket.h
Labels: refactoring

#1964 Fix inclusive `parseUntil` condition in the main packet parse loop.
  Packet++/src/Packet.cpp
  Tests/Packet++Test/TestDefinition.h
  Tests/Packet++Test/Tests/PacketTests.cpp
  Tests/Packet++Test/main.cpp
  Tests/PcppTestUtilities/Resources.cpp
  Tests/PcppTestUtilities/Resources.h
Labels: bug, refactoring
