Repository seladb/PcapPlusPlus, pull requests merged in 2025-10, with the labels that each got.

#1978 Added public headers as private target sources.
  Common++/CMakeLists.txt
  Packet++/CMakeLists.txt
  Pcap++/CMakeLists.txt
Labels: build, refactoring

#1983 Auto precommit update
  .pre-commit-config.yaml
  Examples/IPFragUtil/README.md
  Examples/PcapSplitter/main.cpp
Labels: automated-pr

#1986 Deprecate match filter with packet
  Examples/IPDefragUtil/main.cpp
  Examples/IPFragUtil/main.cpp
  Examples/PcapSplitter/SimpleSplitters.h
  Pcap++/header/PcapDevice.h
  Pcap++/header/PcapFilter.h
  Pcap++/src/PcapDevice.cpp
  Pcap++/src/PcapFileDevice.cpp
  Tests/Pcap++Test/Tests/FilterTests.cpp
Labels: refactoring, API deprecation
