Repository seladb/PcapPlusPlus, pull requests merged in 2025-01, with the labels that each got.

#1672 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1673 Auto precommit update
  .pre-commit-config.yaml
  Examples/KniPong/main.cpp
Labels: automated-pr

#1660 Reformat Pcap++ documentation to use triple-slash doxygen format.
  Pcap++/header/Device.h
  Pcap++/header/DeviceUtils.h
  Pcap++/header/DpdkDevice.h
  Pcap++/header/DpdkDeviceList.h
  Pcap++/header/KniDevice.h
  Pcap++/header/KniDeviceList.h
  Pcap++/header/LinuxNicInformationSocket.h
  Pcap++/header/MBufRawPacket.h
  Pcap++/header/NetworkUtils.h
  Pcap++/header/PcapDevice.h
  Pcap++/header/PcapFileDevice.h
  Pcap++/header/PcapFilter.h
  Pcap++/header/PcapLiveDevice.h
  Pcap++/header/PcapLiveDeviceList.h
  Pcap++/header/PcapRemoteDevice.h
  Pcap++/header/PcapRemoteDeviceList.h
  Pcap++/header/PcapUtils.h
  Pcap++/header/PfRingDevice.h
  Pcap++/header/PfRingDeviceList.h
  Pcap++/header/RawSocketDevice.h
  Pcap++/header/WinPcapLiveDevice.h
  Pcap++/header/XdpDevice.h
  Pcap++/src/DpdkDevice.cpp
  Pcap++/src/KniDevice.cpp
  Pcap++/src/KniDeviceList.cpp
  Pcap++/src/MBufRawPacket.cpp
  Pcap++/src/NetworkUtils.cpp
  Pcap++/src/PcapDevice.cpp
  Pcap++/src/PcapFileDevice.cpp
  Pcap++/src/PcapLiveDevice.cpp
  Pcap++/src/PcapRemoteDeviceList.cpp
  Pcap++/src/PfRingDeviceList.cpp
  Pcap++/src/RawSocketDevice.cpp
Labels: documentation, refactoring

#1596 Overhaul of the Logging Infrastructure
  .codespellrc
  Common++/CMakeLists.txt
  Common++/header/IpAddress.h
  Common++/header/Logger.h
  Common++/header/ObjectPool.h
  Common++/src/IpAddress.cpp
  Common++/src/IpUtils.cpp
  Common++/src/Logger.cpp
  Examples/KniPong/main.cpp
  Examples/PfRingExample-FilterTraffic/main.cpp
  Pcap++/src/NetworkUtils.cpp
  Pcap++/src/PcapLiveDevice.cpp
  Pcap++/src/PcapLiveDeviceList.cpp
  Pcap++/src/PcapRemoteDeviceList.cpp
  Tests/Packet++Test/main.cpp
  Tests/Pcap++Test/CMakeLists.txt
  Tests/Pcap++Test/TestDefinition.h
  Tests/Pcap++Test/Tests/LoggerTests.cpp
  Tests/Pcap++Test/Tests/ObjectPoolTests.cpp
  Tests/Pcap++Test/main.cpp
Labels: refactoring, breaking change
