Repository seladb/PcapPlusPlus, pull requests merged in 2025-04, with the labels that each got.

#1757 Auto precommit update
  .pre-commit-config.yaml
Labels: automated-pr

#1756 Auto OUI Database Update
  3rdParty/OUIDataset/PCPP_OUIDataset.json
Labels: automated-pr

#1764 Changed param `pfring**` to `pfring*&`.
  Pcap++/header/PfRingDevice.h
  Pcap++/src/PfRingDevice.cpp
Labels: refactoring

#1766 Changed MAX_TRIES from macro define to constexpr.
  Pcap++/src/PfRingDevice.cpp
Labels: refactoring

#1748 Templated next layer sub-construction.
  Packet++/CMakeLists.txt
  Packet++/header/ArpLayer.h
  Packet++/header/IPLayer.h
  Packet++/header/IPv4Layer.h
  Packet++/header/IPv6Layer.h
  Packet++/header/IgmpLayer.h
  Packet++/header/Layer.h
  Packet++/header/MplsLayer.h
  Packet++/header/PayloadLayer.h
  Packet++/header/StpLayer.h
  Packet++/header/TpktLayer.h
  Packet++/header/VlanLayer.h
  Packet++/header/VrrpLayer.h
  Packet++/src/EthLayer.cpp
  Packet++/src/IPLayer.cpp
  Packet++/src/IPv4Layer.cpp
  Packet++/src/TcpLayer.cpp
Labels: refactoring

#1767 Change Cmake to use target_compiler_features than CMAKE_CXX_STANDARD to define cpp standard.
  CMakeLists.txt
  Common++/CMakeLists.txt
  Packet++/CMakeLists.txt
  Pcap++/CMakeLists.txt
Labels: build

#1765 Changed `m_PfRingDescriptors` to only contain active channels.
  Pcap++/header/PfRingDevice.h
  Pcap++/src/PfRingDevice.cpp
Labels: refactoring

#1787 Added a custom deleter extension point to `PointerVector`.
  Common++/header/PointerVector.h
Labels: enhancement

#1784 Cleanup of WinPcapLiveDevice::sendPackets.
  Pcap++/src/WinPcapLiveDevice.cpp
Labels: refactoring

#1786 Refactored blocking mode to precompute timeout
  Pcap++/src/PcapLiveDevice.cpp
Labels: refactoring

#1763 Added cmake switch to control the building of Pcap++ subproject.
  .github/workflows/build_and_test.yml
  CMakeLists.txt
  Tests/CMakeLists.txt
  ci/run_tests/run_tests.py
Labels: enhancement, build

#1791 Simplified function names for fetching pcap live devices.
  Examples/ArpSpoofing/main.cpp
  Examples/Arping/main.cpp
  Examples/DNSResolver/main.cpp
  Examples/DnsSpoofing/main.cpp
  Examples/HttpAnalyzer/main.cpp
  Examples/IcmpFileTransfer/Common.cpp
  Examples/IcmpFileTransfer/IcmpFileTransfer-catcher.cpp
  Examples/IcmpFileTransfer/IcmpFileTransfer-pitcher.cpp
  Examples/SSLAnalyzer/main.cpp
  Examples/TLSFingerprinting/main.cpp
  Examples/TcpReassembly/main.cpp
  Examples/Tutorials/Tutorial-LiveTraffic/main.cpp
  Pcap++/header/PcapLiveDeviceList.h
  Pcap++/src/PcapLiveDeviceList.cpp
  Tests/Pcap++Test/Tests/FilterTests.cpp
  Tests/Pcap++Test/Tests/IpMacTests.cpp
  Tests/Pcap++Test/Tests/LiveDeviceTests.cpp
  Tests/Pcap++Test/Tests/PfRingTests.cpp
  Tests/Pcap++Test/Tests/XdpTests.cpp
Labels: refactoring

#1790 Added `internal::DeviceListBase` as a common base for device list classes.
  Pcap++/CMakeLists.txt
  Pcap++/header/DeviceListBase.h
  Pcap++/header/PcapLiveDeviceList.h
  Pcap++/src/PcapLiveDeviceList.cpp
Labels: refactoring
